add a generic function for cmd exist or not

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,6 +1,6 @@
 # -*- mode: sh -*-
 #
-#  Copyright (c) 2016 - 2017 Jeong Han Lee
+#  Copyright (c) 2016 - 2024 Jeong Han Lee
 #  Copyright (c) 2016 - 2017 European Spallation Source ERIC
 #
 #  The program is free software: you can redistribute
@@ -18,8 +18,6 @@
 #
 #  Author  : Jeong Han Lee
 #  Email   : jeonghan.lee@gmail.com
-#  Date    : Friday, August 25 10:29:50 CEST 2017
-#  Version : 0.0.7
 
 
 ROOT_UID=0 
@@ -32,6 +30,17 @@ function popd()  { builtin popd  "$@" > /dev/null; }
 
 function __ini_func() { printf "\n>>>> You are entering in  : %s\n" "${1}"; }
 function __end_func() { printf "\n<<<< You are leaving from : %s\n" "${1}"; }
+
+function cmd_exist(){
+    local COMMAND_CMD
+    if ! command -v ${COMMAND_CMD} &> /dev/null
+    then
+        echo ""
+        echo ">>>>>>>>>> ${COMMAND_CMD} is required. Please install it first."
+        echo ""
+        exit 1
+    fi
+}
 
 function __checkstr() {
     if [ -z "$1" ]; then
